/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/w9AZEZq
 */
import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { LoaderPage } from '@/components/loader-page';

export function LandingPage(props: { onVideoUrl: (videoId: string) => void }) {
  const [videoUrl, setVideoUrl] = useState<string>('');

  const submitHandler = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    props.onVideoUrl(videoUrl);
  };

  return (
    <section className="w-full h-screen py-12 md:py-24 lg:py-32 xl:py-48 bg-black">
      {/* mx-auto option을 추가하여, 중앙으로 정렬 */}
      <div className="container px-4 md:px-6 mx-auto">
        <div className="grid gap-6 items-center">
          <div className="flex flex-col justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-500">
                Analyze Your YouTube Video.
              </h1>
<<<<<<< HEAD
              <p className="max-w-[600px] text-zinc-950 md:text-xl  mx-auto">
=======
              <p className="max-w-[600px] text-zinc-200 md:text-xl dark:text-zinc-100 mx-auto">
>>>>>>> parent of 65ed65b (hofix(fe): landing page 색깔 변경)
                Enter your YouTube video URL and get a detailed analysis.
              </p>
            </div>
            <div className="w-full max-w-sm space-y-2 mx-auto">
              <form className="flex space-x-2" onSubmit={submitHandler}>
                <Input
                  className="max-w-lg flex-1 bg-gray-800 text-white border-gray-900"
                  placeholder="Enter your YouTube video URL"
                  onChange={(event) => setVideoUrl(event.target.value)}
                  type="url"
                />
                <Button className="bg-zinc-50 text-black" type="submit">
                  Analyze
                </Button>
              </form>
<<<<<<< HEAD
              <p className="text-xs text-zinc-950">
=======
              <p className="text-xs text-zinc-200 dark:text-zinc-100">
>>>>>>> parent of 65ed65b (hofix(fe): landing page 색깔 변경)
                Get ready to analyze your YouTube video.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
